---
name: X-Road initialization scenario
author: Raido Kaju <raido.kaju@niis.org>
description: Sets up the X-Road instance for GMT testing

compose-file: !include Docker/xrd-dev-stack/compose.yaml
services:
  cs:
    image: ghcr.io/nordic-institute/xrddev-central-server:latest
  ss0:
    image: ghcr.io/nordic-institute/xrddev-security-server:latest
  ss1:
    image: ghcr.io/nordic-institute/xrddev-security-server:latest
  testca:
    image: ghcr.io/nordic-institute/xrddev-testca:latest
  issoap:
    image: niis/example-adapter:latest
  isrest:
    volumes:
      - ./Docker/xrd-dev-stack/wiremock_mappings:/home/wiremock/mappings
  hurl:
    volumes:
      - ./Docker/xrd-dev-stack/hurl-src:/hurl-src:ro
      - ca-volume:/hurl-files/ca:ro
    # Workaround to keep the hurl container running so that we can do the setup, which runs an exec command
    command: --interactive hurl-src/setup.hurl
    setup-commands:
      - hurl --insecure --variables-file /hurl-src/vars.env --file-root /hurl-files /hurl-src/setup.hurl --very-verbose --retry 18 --retry-interval 10000


flow:
  - name: Initialize
    container: testca
    commands:
      - type: console
        command: ping -c 100 cs
        note: Starting hurl initialization flow
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
        read-sci-stdout: true
